### ISSUE TITLE
Find how system.map is accessed in linux

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#12]
This will be useful context for writing the usermode and plugin components.

**Comment by rhit-frantzag** [comment]
System.map is a map of various kernel symbols and their physical addresses. It is mainly used by ps, though many other services use /proc/kallsyms which is created at runtime and serves a similar function. System.map is an actual file (meaning stored in the filesystem statically), and tends to be located in one of the following locations: "/boot/", "/lib/modules/{kernel version}/", "/usr/src/linux/", and the root folder.

**Comment by rhit-frantzag** [comment]
Worked on by Aidan Frantz and Evan Bestic.
