### ISSUE TITLE
Set up Pylint with some reasonable rules to run on commit

### ISSUE THREAD

**Issue by rhit-frantzag** [rhit-seilerar/exert-capstone#13]
This should run anytime any of us commit to the repository. Setting it up should be reasonably easy, we should ideally also have one for C but that probably requires more research.

**Comment by rhit-seilerar** [comment]
We want it to run the tests too

**Comment by rhit-frantzag** [comment]
Worked on by pair programming from Stephanie and Aidan.

**Comment by rhit-frantzag** [comment]
The tests will be extremely easy to add, they will just require some new workflow stuff
