### ISSUE TITLE
Run the workflows with a git hook

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#16]

**Comment by rhit-frantzag** [comment]
Worked on by Aidan Frantz and Evan Bestic. Server-side hooks are impossible without Github Enterprise and local hooks aren't included in version control and are only guaranteed to work on the person's system, so they are not the ideal way to do this. Instead, we must use branches and Github actions to run the checks before we push to master.

**Comment by rhit-seilerar** [comment]
Closed: this is outside of scope.
