### ISSUE TITLE
Add PyTest

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#19]
- Rewrite our tests to use pytest
- Once the frontend refactor is done, install pytest automatically if a -d/--dev flag is given
- Get @rhit-seilerar to add it to branch rules

**Comment by rhit-frantzag** [comment]
Update: Aria and Aidan spent one hour getting the initial work for this setup. Further work on how to best test exert.py will need to be done, we added more unit tests to make sure we had good code coverage of our existing utilities.
