### ISSUE TITLE
Use get_current() to get the tasklist

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#20]
- Instead of using the ground truth, use the method for getting the tasklist outlined [here](https://kernelnewbies.org/FAQ/get_current) to get the tasklist
- Use the ground truth to test some known offsets from it.

**Comment by rhit-frantzag** [comment]
Update: Aidan and Aria paired for 3 hours. We've found the two ways Linux stores its current_task and written code to obtain it from one. However, it is not giving the expected result and the other option is blocked on communication with the client.
