### ISSUE TITLE
Compile the usermode program with the cross-compiler docker container

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#21]
- Once the frontend is refactored:
  - Automatically run the tools docker container, mounted with the capstone repo
  - Build within the container
  - Run the panda container
  - Verify that you can run the result in the panda container

**Comment by rhit-frantzag** [comment]
Stephanie and I (Aidan Frantz) teamed on this project for one hour, which we mainly spent researching how argument parsing in Python works so that we could effectively extend the current system.

**Comment by rhit-morehask** [comment]
Wrote how to test in test.md, added a dev option to compile usermode program and we verified that it works.
