### ISSUE TITLE
Make the ramdisk run commands

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#30]
Currently PANDA simply exits when running the ramdisk because something is wrong with the formatting. The incorrect ramdisk formatting must be corrected, and commands to build and use the ramdisk need to be implemented.

**Comment by rhit-frantzag** [comment]
Evan and I have successfully generated a working ramdisk for x86_64 and are working on how to do so for ARM (the most important part is determining the specific ARM version that the kernel requires). We also researched how Panda expect prompts work.
