### ISSUE TITLE
Allow exert.py to run within a container

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#32]
- Add the '-d', '--docker' top-level option. If present, assume we're running in a docker container
- If -d is specified, modify all docker commands to instead just run locally
  - For example, 'docker exec --it {command}' would just become '{command}'
- If you can't run it locally (e.g. 'docker stop pandare'), warn about that and don't do anything
- For now, for the tools container, we can either use docker-in-docker or cross-container communication. The former is likely easier, but the latter is preferable.

**Comment by rhit-bestice** [comment]
Paired with Aidan so far. 3 hours tonight.

**Comment by rhit-bestice** [comment]
Paired 1 hour with Stephanie. Task complete and pushed.
