### ISSUE TITLE
Determine which board the generic ARM QCOW is using in PANDA

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#39]
This will make some of the other tickets significantly easier. Specifically, it should help us determine the right value for the board parameter, which will narrow our search for the correct ARM configuration.

**Comment by rhit-frantzag** [comment]
Evan and I have discovered that the generic ARM qcow in Panda uses the versatilepb machine. I have confirmed that this machine is capable of starting the ARM kernel I originally sourced from Panda. I am very pleased, and the other tickets should now hopefully go much faster.
