### ISSUE TITLE
Look into the linux syscall ABI

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#6]
The linux syscall ABI is the specification for which parameters are put into which registers, so that the syscalls know where to find them.  We want to know the specifics. There should be plenty of guides online about this.

Worked on by: Stephanie and Evan

**Comment by rhit-morehask** [comment]
We found several links to official documentation and other resources that explain how and why linux syscall is used. Time: 1 hour
